### ISSUE TITLE
Select a licence

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/javafx-collections#2]
@qparis, @plata any suggestion?

**Comment by qparis** [comment]
It is up to you, as long as it is compatible with phoenicis license. After all, you own the copyright of this piece of code.

I suggest MIT or Apache2 for this kind of library.

**Comment by madoar** [comment]
Then let's go with MIT. Whom should I add as the owner of the repository? (Github asks this information when choosing a licence)

**Comment by plata** [comment]
Probably @qparis then.

**Comment by qparis** [comment]
Do you want me to add the license file?

**Comment by madoar** [comment]
Yes, feel free to do so :)

**Comment by qparis** [comment]
What full name should I use as copyright holder?

**Comment by madoar** [comment]
I don't know, what do you suggest?

**Comment by qparis** [comment]
Should be your name theoritically because you wrote the program.

**Comment by qparis** [comment]
We can use "madoar" if you want

**Comment by madoar** [comment]
Ok, then lets use my name `Marc Arndt`

**Comment by qparis** [comment]
Done

**Comment by madoar** [comment]
Thanks
